// CEDATProtocol.cpp was generated by ProtoGen version 3.2.a

#include "CEDATProtocol.hpp"

/*!
 * \brief Lookup label for 'Packets' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry
 */
const char* Packets_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case CEDAT_FILE_INFO:
        return translateCEDAT("CEDAT_FILE_INFO");
    case CEDAT_NEW_VAR:
        return translateCEDAT("CEDAT_NEW_VAR");
    case CEDAT_DATAPOINT:
        return translateCEDAT("CEDAT_DATAPOINT");
    case CEDAT_DATAPOINT_BOOLEAN:
        return translateCEDAT("CEDAT_DATAPOINT_BOOLEAN");
    }
}

// end of CEDATProtocol.cpp
