#ifndef LUMBERJACK_VERSION_HPP
#define LUMBERJACK_VERSION_HPP

#include <QString>

const QString LUMBERJACK_VERSION_STRING = "0.0.1";

#define LUMBERJACK_BUILD_DATE __DATE__
#define LUMBERJACK_BUILD_TIME __TIME__

#endif // LUMBERJACK_VERSION_HPP
