# Run code style tests

name: Code Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  clang-tidy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ignore: "build|plugins|fft|qwt|ui_tmp|unit_test|pythonqt"
        ignore-format: "build|plugins|fft|qwt|ui_tmp|unit_test|pythonqt"
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
    - name: Failure
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1