# Run code style tests

name: Code Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      with:
        scandir: 'src'
        builddir: 'build'