# Run unit tests

name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt 
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.13.2
    - name: Build qwt
      run: |
        cd qwt
        qmake qwt.pro
        make
    - name: Run Unit Tests
      run: |
        ls qwt/lib
        cp qwt/lib/libqwtd* unit_test/debug
        cd unit_test
        qmake CONFIG+=debug
        make
        cd debug
  