# Run unit tests

name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Qt 
      uses: jurplel/install-qt-action@v2
    - name: Build qwt
      run: |
        cd qwt
        qmake
        make
        make install
    - name: Run Unit Tests
      run: |
        cd unit_test
        qmake
        make
        
