# Run unit tests

name: tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Qt 
      uses: actions/install-qt-action@v2

    - name: Run Unit Tests
      run: |
        cd unit_test
        qmake
